SELECT	DEPOSITOR.CUSTOMER_NAME
FROM	ACCOUNT
		INNER JOIN DEPOSITOR
		ON 	DEPOSITOR.ACCOUNT_NUMBER
			=
			ACCOUNT.ACCOUNT_NUMBER
WHERE	ACCOUNT.BALANCE > 500;

PREPARE customer500 (int) AS
    SELECT	DEPOSITOR.CUSTOMER_NAME
    FROM	ACCOUNT
            INNER JOIN DEPOSITOR
            ON 	DEPOSITOR.ACCOUNT_NUMBER
                =
                ACCOUNT.ACCOUNT_NUMBER
    WHERE	ACCOUNT.BALANCE > $1;

execute customer500(500);
