SELECT	BRANCH.BRANCH_CITY
FROM	LOAN
		INNER JOIN BRANCH
		ON 	BRANCH.BRANCH_NAME
			=
			LOAN.BRANCH_NAME
WHERE	LOAN.AMOUNT BETWEEN 1000 AND 2000;

PREPARE BRANCHCITY (INT) AS
SELECT	BRANCH.BRANCH_CITY
FROM	LOAN
		INNER JOIN BRANCH
		ON 	BRANCH.BRANCH_NAME
			=
			LOAN.BRANCH_NAME
WHERE	LOAN.AMOUNT BETWEEN $1 AND $2;

EXECUTE BRANCHCITY(1000, 2000);