SELECT	SUM(ACCOUNT.BALANCE) TOTAL_AMOUNT
FROM	BORROWER
		INNER JOIN DEPOSITOR
		ON	DEPOSITOR.CUSTOMER_NAME
			=
			BORROWER.CUSTOMER_NAME
		INNER JOIN ACCOUNT
		ON 	ACCOUNT.ACCOUNT_NUMBER
			=
			DEPOSITOR.ACCOUNT_NUMBER
WHERE	BORROWER.LOAN_NUMBER = 'L-15';